package SistemaBibliotecario.VistaLogin;

import java.awt.*;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.*;
import javax.swing.*;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;
import SistemaBibliotecario.Conexion.ConexionMySQL;
import SistemaBibliotecario.Modelos.PasswordUtil;

/**
 * Registro de Lector - Estilo Moderno
 */
public class Register extends javax.swing.JPanel {

    // --- Paleta de Colores (Coherente con el Login) ---
    private final Color COLOR_PRIMARY = new Color(20, 40, 80); // Azul Oscuro
    private final Color COLOR_ACCENT = new Color(52, 152, 219); // Celeste Brillante
    private final Color COLOR_HOVER = new Color(40, 70, 120); // Azul Medio
    private final Color COLOR_TEXT_LABEL = new Color(44, 62, 80); // Gris Oscuro Texto
    private final Color COLOR_BG = Color.WHITE;

    public Register() {
        initComponents();
        personalizarInterfaz(); // <--- AQUÍ APLICAMOS EL ESTILO
    }

    /**
     * Método para aplicar colores y estilos modernos sin romper el diseño
     */
    private void personalizarInterfaz() {
        this.setBackground(COLOR_BG);

        // 1. Estilo del Título Principal
        jLabelTitulo.setForeground(COLOR_PRIMARY);
        jLabelTitulo.setFont(new Font("Segoe UI", Font.BOLD, 36));
        jLabelTitulo.setText("REGISTRO DE LECTORES");

        // 2. Estilizar todas las etiquetas (Labels)
        JLabel[] labels = {
                jLabel14, jLabel16, jLabel17, jLabel18, jLabel19,
                jLabel20, jLabel21, jLabel22, jLabel23
        };

        for (JLabel lbl : labels) {
            lbl.setForeground(COLOR_TEXT_LABEL);
            lbl.setFont(new Font("Segoe UI", Font.BOLD, 14));
        }

        // 3. Estilizar Campos de Texto (Inputs)
        JTextField[] inputs = {
                txtDni, txtNombre, txtApellidoP, txtApellidoM,
                txtDireccion, txtTelefono, txtEmail
        };
        for (JTextField tf : inputs) {
            estilizarInput(tf);
        }
        estilizarInput(jPasswordFieldContrasena);
        estilizarInput(jPasswordFieldConfirmarContrasena);

        // 4. Estilizar Botones
        estilizarBoton(btnRegistrarse, COLOR_PRIMARY, Color.WHITE);
        estilizarBoton(btnRegresar, new Color(149, 165, 166), Color.WHITE); // Gris para "Regresar"
    }

    private void estilizarInput(JComponent campo) {
        campo.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        campo.setBackground(Color.WHITE);
        // Borde gris suave inicial
        campo.setBorder(new CompoundBorder(
                new LineBorder(new Color(200, 200, 200)),
                new EmptyBorder(5, 10, 5, 10)));

        // Evento para cambiar color al hacer clic
        campo.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                campo.setBorder(new CompoundBorder(
                        new LineBorder(COLOR_ACCENT, 2), // Borde azul brillante
                        new EmptyBorder(5, 10, 5, 10)));
            }

            @Override
            public void focusLost(FocusEvent e) {
                campo.setBorder(new CompoundBorder(
                        new LineBorder(new Color(200, 200, 200)),
                        new EmptyBorder(5, 10, 5, 10)));
            }
        });
    }

    private void estilizarBoton(JButton btn, Color fondo, Color texto) {
        btn.setBackground(fondo);
        btn.setForeground(texto);
        btn.setFont(new Font("Segoe UI", Font.BOLD, 16));
        btn.setFocusPainted(false);
        btn.setBorderPainted(false); // Quitar borde 3D
        btn.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // Hover Effect
        btn.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                btn.setBackground(fondo.darker());
            }

            @Override
            public void mouseExited(MouseEvent e) {
                btn.setBackground(fondo);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellidoP = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPasswordFieldConfirmarContrasena = new javax.swing.JPasswordField();
        jPasswordFieldContrasena = new javax.swing.JPasswordField();
        btnRegistrarse = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        // Eliminé los duplicados de Títulos y dejé solo este
        jLabelTitulo.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 102));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("REGISTRO DE LECTORES");
        add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 470, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setText("Dni");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 40, 20));
        add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 180, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("Nombres");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 100, 20));
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 180, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Apellido Paterno");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, 20));
        add(txtApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 180, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("Apellido Materno");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 180, 20));
        add(txtApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 180, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("Direccion");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 120, 20));
        add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 180, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("Telefono");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 100, 20));
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 180, 30));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("Email");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 80, 20));
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 180, 30));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("Contraseña");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 110, 20));
        add(jPasswordFieldContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 180, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Confirmar Contraseña");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 220, 20));
        add(jPasswordFieldConfirmarContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 180, 30));

        btnRegistrarse.setBackground(new java.awt.Color(19, 38, 76));
        btnRegistrarse.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        btnRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarse.setText("REGISTRARSE");
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });
        add(btnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 180, 40));

        btnRegresar.setBackground(new java.awt.Color(19, 38, 76));
        btnRegresar.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 140, 40));
    }// </editor-fold>

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {
        // 1. OBTENER DATOS (Asegúrate de usar .trim() para limpiar espacios)
        String dni = txtDni.getText().trim();
        String nombre = txtNombre.getText().trim();
        String apellidoP = txtApellidoP.getText().trim();
        String apellidoM = txtApellidoM.getText().trim();
        String direccion = txtDireccion.getText().trim();
        String telefono = txtTelefono.getText().trim();
        String email = txtEmail.getText().trim();

        // Para contraseñas NO uses trim() intermedio, pero sí verifica que no sea puro
        // espacio al inicio/final si quieres
        String contrasena = new String(jPasswordFieldContrasena.getPassword());
        String confirmarContrasena = new String(jPasswordFieldConfirmarContrasena.getPassword());

        // 2. VALIDACIONES (El orden importa: de lo más simple a lo más complejo)

        // A) Campos Vacíos
        if (dni.isEmpty() || nombre.isEmpty() || apellidoP.isEmpty() || apellidoM.isEmpty() ||
                direccion.isEmpty() || telefono.isEmpty() || email.isEmpty() ||
                contrasena.isEmpty() || confirmarContrasena.isEmpty()) {

            JOptionPane.showMessageDialog(this, "⚠️ Por favor, complete todos los campos.", "Campos Incompletos",
                    JOptionPane.WARNING_MESSAGE);
            return; // <--- ¡MUY IMPORTANTE! Detiene la ejecución aquí.
        }

        // B) Coincidencia de Contraseñas
        if (!contrasena.equals(confirmarContrasena)) {
            JOptionPane.showMessageDialog(this, "❌ Las contraseñas no coinciden.", "Error de Contraseña",
                    JOptionPane.ERROR_MESSAGE);
            // Limpiamos los campos de contraseña para que intente de nuevo
            jPasswordFieldContrasena.setText("");
            jPasswordFieldConfirmarContrasena.setText("");
            return; // Detener
        }

        // C) Longitud de Contraseña
        if (contrasena.length() < 6) {
            JOptionPane.showMessageDialog(this, "⚠️ La contraseña es muy débil. Use al menos 6 caracteres.",
                    "Seguridad", JOptionPane.WARNING_MESSAGE);
            return; // Detener
        }

        // D) Formato DNI (Debe ser numérico y de 8 dígitos)
        if (!dni.matches("\\d{8}")) {
            JOptionPane.showMessageDialog(this, "⚠️ El DNI debe tener exactamente 8 números.", "DNI Inválido",
                    JOptionPane.WARNING_MESSAGE);
            return; // Detener
        }

        // E) Formato Email (Validación básica)
        if (!email.matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
            JOptionPane.showMessageDialog(this, "⚠️ El formato del correo electrónico no es válido.", "Email Inválido",
                    JOptionPane.WARNING_MESSAGE);
            return; // Detener
        }

        // --- SI LLEGA AQUÍ, TODO ESTÁ VALIDADO ---

        String rol = "lector";
        Connection conn = null;
        PreparedStatement psPersona = null;
        PreparedStatement psUsuario = null;
        ResultSet rs = null;

        try {
            conn = ConexionMySQL.getInstancia().getConexion();
            conn.setAutoCommit(false); // Inicio Transacción

            // 3. VALIDACIONES DE BASE DE DATOS (Duplicados)
            if (existeDato(conn, "dni", dni)) {
                JOptionPane.showMessageDialog(this, "⛔ El DNI ingresado ya existe en el sistema.", "DNI Duplicado",
                        JOptionPane.ERROR_MESSAGE);
                return; // Detener
            }
            if (existeDato(conn, "email", email)) {
                JOptionPane.showMessageDialog(this, "⛔ El correo ingresado ya está registrado.", "Correo Duplicado",
                        JOptionPane.ERROR_MESSAGE);
                return; // Detener
            }

            // 4. INSERCIÓN (Esto solo pasa si no hubo return antes)

            // Insertar Persona
            String sqlPersona = "INSERT INTO persona (dni, nombre, apellido_p, apellido_m, direccion, telefono, email) VALUES (?, ?, ?, ?, ?, ?, ?)";
            psPersona = conn.prepareStatement(sqlPersona, Statement.RETURN_GENERATED_KEYS);
            psPersona.setString(1, dni);
            psPersona.setString(2, nombre);
            psPersona.setString(3, apellidoP);
            psPersona.setString(4, apellidoM);
            psPersona.setString(5, direccion);
            psPersona.setString(6, telefono);
            psPersona.setString(7, email);
            psPersona.executeUpdate();

            rs = psPersona.getGeneratedKeys();
            int idPersona = 0;
            if (rs.next())
                idPersona = rs.getInt(1);

            // Insertar Usuario
            String sqlUsuario = "INSERT INTO usuario (id_persona, contrasena, rol) VALUES (?, ?, ?)";
            psUsuario = conn.prepareStatement(sqlUsuario);
            psUsuario.setInt(1, idPersona);
            psUsuario.setString(2, PasswordUtil.hashPassword(contrasena)); // Encriptar
            psUsuario.setString(3, rol);
            psUsuario.executeUpdate();

            conn.commit(); // Confirmar cambios

            JOptionPane.showMessageDialog(this, "✅ Registro exitoso.\nBienvenido al sistema.", "Éxito",
                    JOptionPane.INFORMATION_MESSAGE);
            redirigirALogin();

        } catch (SQLException e) {
            // Manejo de errores SQL
            try {
                if (conn != null)
                    conn.rollback();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "❌ Error de base de datos:\n" + e.getMessage(), "Error Crítico",
                    JOptionPane.ERROR_MESSAGE);
        } finally {
            // Cerrar recursos
            try {
                if (rs != null)
                    rs.close();
                if (psPersona != null)
                    psPersona.close();
                if (psUsuario != null)
                    psUsuario.close();
                if (conn != null)
                    conn.setAutoCommit(true);
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {
        redirigirALogin();
    }

    private boolean existeDato(Connection conn, String col, String val) throws SQLException {
        String sql = "SELECT COUNT(*) FROM persona WHERE " + col + " = ?";
        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, val);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next())
                    return rs.getInt(1) > 0;
            }
        }
        return false;
    }

    private void redirigirALogin() {
        login loginWindow = new login();
        loginWindow.setLocationRelativeTo(null);
        loginWindow.setVisible(true);
        java.awt.Window w = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (w != null)
            w.dispose();
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabelTitulo; // Nombre unificado
    private javax.swing.JPasswordField jPasswordFieldConfirmarContrasena;
    private javax.swing.JPasswordField jPasswordFieldContrasena;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration
}