/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SistemaBibliotecario.vistaBlibliotecario;

import java.awt.BorderLayout;
import java.util.List;
import javax.swing.SwingUtilities;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

import SistemaBibliotecario.Dao.LectorDAO;
import SistemaBibliotecario.Dao.LibroDAO;
import SistemaBibliotecario.Dao.PrestamoDAO;
import SistemaBibliotecario.Modelos.Libro;
import SistemaBibliotecario.Modelos.Prestamo;
import SistemaBibliotecario.Modelos.SesionActual;
import SistemaBibliotecario.VistaLogin.login;
import java.awt.Frame;

/**
 *
 * @author User
 */
public class prestamos extends javax.swing.JPanel {

    /**
     * Creates new form usuarios
     */
    public prestamos() {
        initComponents();
        mostrarTablaPrestamos();
        
        if (SesionActual.nombre != null && !SesionActual.nombre.isEmpty()) {
        lblNombreBibliotecario.setText(" " + SesionActual.nombre);
    } else {
        lblNombreBibliotecario.setText("Bienvenido: Bibliotecario");
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnPrestamos = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnLibros = new javax.swing.JButton();
        lblNombreBibliotecario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrestamosActuales = new javax.swing.JTable();
        txtBuscarPrestamos = new javax.swing.JTextField();
        btnRegistrarDevolucion = new javax.swing.JButton();
        btnRegistrarNPrestamo = new javax.swing.JButton();
        cbxEstadoPrestamo = new javax.swing.JComboBox<>();
        btnVerTodosLosPrestamos = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnMisPrestamos = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("GESTION DE BIBLIOTECARIOS");

        jPanel1.setBackground(new java.awt.Color(236, 240, 241));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(19, 38, 76));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrestamos.setBackground(new java.awt.Color(0, 0, 0));
        btnPrestamos.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnPrestamos.setForeground(new java.awt.Color(255, 255, 255));
        btnPrestamos.setText("PRESTAMOS");
        btnPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestamosActionPerformed(evt);
            }
        });
        jPanel2.add(btnPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 240, 80));

        btnUsuarios.setBackground(new java.awt.Color(0, 51, 102));
        btnUsuarios.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setText("USUARIOS");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        jPanel2.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 240, 80));

        btnInicio.setBackground(new java.awt.Color(0, 51, 102));
        btnInicio.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("INICIO");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        jPanel2.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 99, 240, 80));

        btnReportes.setBackground(new java.awt.Color(0, 51, 102));
        btnReportes.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setText("REPORTES");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        jPanel2.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 240, 80));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BiblioSys");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        btnSalir.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 621, 240, 44));

        btnLibros.setBackground(new java.awt.Color(0, 51, 102));
        btnLibros.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnLibros.setForeground(new java.awt.Color(255, 255, 255));
        btnLibros.setText("LIBROS");
        btnLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibrosActionPerformed(evt);
            }
        });
        jPanel2.add(btnLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 240, 80));

        lblNombreBibliotecario.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        lblNombreBibliotecario.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreBibliotecario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreBibliotecario.setText("                                ");
        lblNombreBibliotecario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(lblNombreBibliotecario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 569, 240, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 700));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.jpeg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 40, 110, 80));

        jPanel3.setBackground(new java.awt.Color(19, 38, 76));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ventana Usuarios");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 8, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 910, 30));

        tblPrestamosActuales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblPrestamosActuales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Dni", "Nombres", "Libro", "Isbn", "Fecha Prestamo", "Fecha Devolucion", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblPrestamosActuales);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 860, 380));

        txtBuscarPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarPrestamosActionPerformed(evt);
            }
        });
        jPanel1.add(txtBuscarPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 550, 30));

        btnRegistrarDevolucion.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnRegistrarDevolucion.setForeground(new java.awt.Color(19, 38, 76));
        btnRegistrarDevolucion.setText("+ Registrar Devolución");
        btnRegistrarDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarDevolucionActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarDevolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, -1, -1));

        btnRegistrarNPrestamo.setBackground(new java.awt.Color(19, 38, 76));
        btnRegistrarNPrestamo.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnRegistrarNPrestamo.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarNPrestamo.setText("+ Registrar Nuevo Prestamo");
        btnRegistrarNPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarNPrestamoActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarNPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        cbxEstadoPrestamo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "activo", "vencido", "devuelto" }));
        jPanel1.add(cbxEstadoPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        btnVerTodosLosPrestamos.setBackground(new java.awt.Color(19, 38, 76));
        btnVerTodosLosPrestamos.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnVerTodosLosPrestamos.setForeground(new java.awt.Color(255, 255, 255));
        btnVerTodosLosPrestamos.setText("Ver todos los prestamos");
        btnVerTodosLosPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTodosLosPrestamosActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerTodosLosPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 270, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel13.setText("Estado");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 50, 20));

        btnBuscar.setBackground(new java.awt.Color(19, 38, 76));
        btnBuscar.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, 140, 40));

        btnMisPrestamos.setBackground(new java.awt.Color(19, 38, 76));
        btnMisPrestamos.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnMisPrestamos.setForeground(new java.awt.Color(255, 255, 255));
        btnMisPrestamos.setText("Mis Prestamos");
        btnMisPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMisPrestamosActionPerformed(evt);
            }
        });
        jPanel1.add(btnMisPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 170, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestamosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrestamosActionPerformed

    private void btnLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibrosActionPerformed
javax.swing.JFrame frame = new javax.swing.JFrame("Gestión de Libros");
    frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
    frame.setContentPane(new SistemaBibliotecario.vistaBlibliotecario.libros()); // agrega el panel
    frame.pack(); // ajusta al tamaño preferido
    frame.setLocationRelativeTo(null); // centra la ventana
    frame.setVisible(true); // muestra la nueva ventana

    // Cierra la ventana actual
    javax.swing.SwingUtilities.getWindowAncestor(this).dispose();            // TODO add your handling code here:
    }//GEN-LAST:event_btnLibrosActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
javax.swing.JFrame frame = new javax.swing.JFrame("Gestión de Usuarios");
    frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
    frame.setContentPane(new SistemaBibliotecario.vistaBlibliotecario.usuarios()); // agrega el panel
    frame.pack(); // ajusta al tamaño preferido
    frame.setLocationRelativeTo(null); // centra la ventana
    frame.setVisible(true); // muestra la nueva ventana

    // Cierra la ventana actual
    javax.swing.SwingUtilities.getWindowAncestor(this).dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void txtBuscarPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarPrestamosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarPrestamosActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
javax.swing.JFrame frame = new javax.swing.JFrame("Gestión de Reportes");
    frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
    frame.setContentPane(new SistemaBibliotecario.vistaBlibliotecario.reportes()); // agrega el panel
    frame.pack(); // ajusta al tamaño preferido
    frame.setLocationRelativeTo(null); // centra la ventana
    frame.setVisible(true); // muestra la nueva ventana

    // Cierra la ventana actual
    javax.swing.SwingUtilities.getWindowAncestor(this).dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnRegistrarNPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarNPrestamoActionPerformed
       String dniBibliotecario = SesionActual.dni;
    String dniUsuario = JOptionPane.showInputDialog(this, "Ingrese el DNI del lector:");
    
    if (dniUsuario == null || dniUsuario.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Operación cancelada o DNI vacío.");
        return;
    }

    // SOLUCIÓN PARA JPanel - obtener la ventana padre
    java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
    JDialog dialog = new JDialog((Frame) parentWindow, "Seleccionar Libro", true);
    dialog.setLayout(new BorderLayout());
    dialog.setSize(700, 400);
    dialog.setLocationRelativeTo(parentWindow); // Usar parentWindow aquí también

    // Modelo de tabla
    String[] columnNames = {"ISBN", "Título", "Autor", "Año", "Stock", "Categoría"};
    DefaultTableModel model = new DefaultTableModel(columnNames, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    JTable table = new JTable(model);
    table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    JScrollPane scrollPane = new JScrollPane(table);
    
    // Botones
    JPanel panelBotones = new JPanel();
    JButton btnSeleccionar = new JButton("Seleccionar");
    JButton btnCancelar = new JButton("Cancelar");
    panelBotones.add(btnSeleccionar);
    panelBotones.add(btnCancelar);

    dialog.add(scrollPane, BorderLayout.CENTER);
    dialog.add(panelBotones, BorderLayout.SOUTH);

    // Cargar libros
    cargarLibrosDisponibles(model);

    final String[] isbnSeleccionado = new String[1];

    btnSeleccionar.addActionListener(e -> {
        int filaSeleccionada = table.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(dialog, "Por favor, seleccione un libro.");
            return;
        }
        isbnSeleccionado[0] = model.getValueAt(filaSeleccionada, 0).toString();
        dialog.dispose();
    });

    btnCancelar.addActionListener(e -> {
        isbnSeleccionado[0] = null;
        dialog.dispose();
    });

    // Doble clic
    table.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            if (evt.getClickCount() == 2) {
                int row = table.rowAtPoint(evt.getPoint());
                if (row >= 0) {
                    isbnSeleccionado[0] = model.getValueAt(row, 0).toString();
                    dialog.dispose();
                }
            }
        }
    });

    dialog.setVisible(true);

    if (isbnSeleccionado[0] == null) {
        JOptionPane.showMessageDialog(this, "Operación cancelada.");
        return;
    }

    // Registrar préstamo
    PrestamoDAO prestamoDAO = new PrestamoDAO();
    boolean exito = prestamoDAO.registrarPrestamo(dniUsuario, isbnSeleccionado[0], dniBibliotecario);

    if (exito) {
        mostrarTablaPrestamos();
        JOptionPane.showMessageDialog(this, "✅ Préstamo registrado correctamente.");
    } else {
        JOptionPane.showMessageDialog(this, "❌ No se pudo registrar el préstamo.", "Error", JOptionPane.ERROR_MESSAGE);
    }
   
    }//GEN-LAST:event_btnRegistrarNPrestamoActionPerformed

    private void btnRegistrarDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarDevolucionActionPerformed
        // Obtener la fila seleccionada en la tabla
    int filaSeleccionada = tblPrestamosActuales.getSelectedRow();
    
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "⚠️ Por favor, seleccione un préstamo de la tabla para registrar la devolución.");
        return;
    }
    
    // Obtener los datos de la fila seleccionada
    String dniLector = tblPrestamosActuales.getValueAt(filaSeleccionada, 0).toString();
    String nombresLector = tblPrestamosActuales.getValueAt(filaSeleccionada, 1).toString();
    String tituloLibro = tblPrestamosActuales.getValueAt(filaSeleccionada, 2).toString();
    String isbn = tblPrestamosActuales.getValueAt(filaSeleccionada, 3).toString();
    String estado = tblPrestamosActuales.getValueAt(filaSeleccionada, 6).toString();
    
    // Verificar que el préstamo esté activo
    if ("devuelto".equalsIgnoreCase(estado)) {
        JOptionPane.showMessageDialog(this, "⚠️ Este préstamo ya fue devuelto.");
        return;
    }
    
    try {
        // Obtener el ID del préstamo
        PrestamoDAO prestamoDAO = new PrestamoDAO();
        int idPrestamo = prestamoDAO.obtenerIdPrestamoPorDniEIsbn(dniLector, isbn, SesionActual.dni);
        
        if (idPrestamo == -1) {
            JOptionPane.showMessageDialog(this, "❌ No se pudo identificar el préstamo seleccionado.");
            return;
        }
        
        // Verificar si hay retraso
        int diasRetraso = prestamoDAO.verificarRetrasoPrestamo(idPrestamo);
        
        String mensajeConfirmacion;
        if (diasRetraso > 0) {
            mensajeConfirmacion = "⚠️ PRÉSTAMO CON RETRASO\n\n" +
                                "Lector: " + nombresLector + " (" + dniLector + ")\n" +
                                "Libro: " + tituloLibro + "\n" +
                                "Días de retraso: " + diasRetraso + "\n" +
                                "Multa a aplicar: S/ " + (diasRetraso * 2.0) + "\n\n" +
                                "¿Desea registrar la devolución con multa?";
        } else {
            mensajeConfirmacion = "¿Está seguro de registrar la devolución?\n\n" +
                                "Lector: " + nombresLector + " (" + dniLector + ")\n" +
                                "Libro: " + tituloLibro;
        }
        
        // Confirmar la devolución
        int confirmacion = JOptionPane.showConfirmDialog(this,
            mensajeConfirmacion,
            "Confirmar Devolución",
            JOptionPane.YES_NO_OPTION,
            diasRetraso > 0 ? JOptionPane.WARNING_MESSAGE : JOptionPane.QUESTION_MESSAGE);
        
        if (confirmacion != JOptionPane.YES_OPTION) {
            return;
        }
        
        // Registrar la devolución
        boolean exito = prestamoDAO.registrarDevolucion(idPrestamo, SesionActual.dni);
        
        if (exito) {
            if (diasRetraso > 0) {
                JOptionPane.showMessageDialog(this, 
                    "✅ Devolución registrada con RETRASO\n" +
                    "Días de retraso: " + diasRetraso + "\n" +
                    "Multa aplicada: S/ " + (diasRetraso * 2.0) + "\n" +
                    "Multa registrada en el sistema.\n" +
                    "El usuario ha sido bloqueado hasta pagar la multa.");
            } else {
                JOptionPane.showMessageDialog(this, 
                    "✅ Devolución registrada correctamente.\n" +
                    "El stock del libro ha sido actualizado.");
            }
            mostrarTablaPrestamos(); // Actualizar la tabla
        } else {
            JOptionPane.showMessageDialog(this, "❌ No se pudo registrar la devolución.");
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "❌ Error: " + e.getMessage());
        e.printStackTrace();
    }
        
    }//GEN-LAST:event_btnRegistrarDevolucionActionPerformed

  private void cargarLibrosDisponibles(DefaultTableModel model) {
    try {
        LibroDAO libroDAO = new LibroDAO();
        java.util.List<Object[]> librosDisponibles = libroDAO.obtenerLibrosDisponiblesConCategoria();
        
        // Limpiar la tabla
        model.setRowCount(0);
        
        // Llenar la tabla directamente con los arrays de objetos
        for (Object[] libro : librosDisponibles) {
            model.addRow(libro);
        }
        
        if (librosDisponibles.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay libros disponibles en este momento.");
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar los libros: " + e.getMessage(), 
                                    "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}

private String obtenerNombreCategoria(int idCategoria) {
    // Implementar esta método según tu base de datos
    // Ejemplo simple - deberías adaptarlo a tu sistema
    try {
        String sql = "SELECT nombre FROM categorias WHERE id_categoria = ?";
        // Aquí tu código para ejecutar la consulta y obtener el nombre
        return "Categoría " + idCategoria; // Placeholder
    } catch (Exception e) {
        return "Desconocida";
    }
}

    private void btnVerTodosLosPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTodosLosPrestamosActionPerformed
    mostrarTodosLosPrestamos();


    }//GEN-LAST:event_btnVerTodosLosPrestamosActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
    buscarPrestamos();


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnMisPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMisPrestamosActionPerformed

            mostrarMisPrestamos();


    }//GEN-LAST:event_btnMisPrestamosActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        login view = new login();  
    view.setLocationRelativeTo(null); // Centrar la ventana
    view.setVisible(true); // Mostrar el login

    // Cerrar la ventana actual
    javax.swing.SwingUtilities.getWindowAncestor(this).dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
         javax.swing.JFrame frame = new javax.swing.JFrame("ventana de inicio");
    frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
    frame.setContentPane(new SistemaBibliotecario.vistaBlibliotecario.inicio()); // agrega el panel
    frame.pack(); // ajusta al tamaño preferido
    frame.setLocationRelativeTo(null); // centra la ventana
    frame.setVisible(true); // muestra la nueva ventana

    // Cierra la ventana actual
    javax.swing.SwingUtilities.getWindowAncestor(this).dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioActionPerformed

    public void mostrarTablaPrestamos() {
    try {
        PrestamoDAO prestamoDAO = new PrestamoDAO();
        
        // Obtener préstamos solo del bibliotecario en sesión
        List<Prestamo> listaPrestamos = prestamoDAO.obtenerPrestamosPorBibliotecario(SesionActual.dni);
        
        // DEBUG: Mostrar en consola qué préstamos se están cargando
        System.out.println("=== DEBUG: PRÉSTAMOS ENCONTRADOS PARA BIBLIOTECARIO: " + SesionActual.dni + " ===");
        for (Prestamo p : listaPrestamos) {
            System.out.println("ID: " + p.getIdPrestamo() + 
                             " | Estado: " + p.getEstado() + 
                             " | DNI Lector: " + p.getDniLector() +
                             " | Libro: " + p.getTituloLibro() +
                             " | ISBN: " + p.getIsbn() +
                             " | Fecha Préstamo: " + p.getFechaPrestamo() +
                             " | Fecha Devolución: " + p.getFechaDevolucion());
        }
        System.out.println("Total préstamos encontrados: " + listaPrestamos.size());
        System.out.println("==========================================");
        
        DefaultTableModel modelo = (DefaultTableModel) tblPrestamosActuales.getModel();
        modelo.setRowCount(0); // Limpiar tabla antes de agregar nuevos datos
        
        for (Prestamo prestamo : listaPrestamos) {
            Object[] fila = {
                prestamo.getDniLector(),
                prestamo.getNombresLector(),
                prestamo.getTituloLibro(),
                prestamo.getIsbn(),
                prestamo.getFechaPrestamo(),
                prestamo.getFechaDevolucion(),
                prestamo.getEstado()
            };
            modelo.addRow(fila);
        }
        
        // Mostrar mensaje informativo
        JOptionPane.showMessageDialog(this, 
            "Se encontraron " + listaPrestamos.size() + " préstamos realizados por usted.",
            "Información", 
            JOptionPane.INFORMATION_MESSAGE);
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar los préstamos: " + e.getMessage(), 
                                    "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
        
        // DEBUG: Mostrar el error completo
        System.out.println("=== ERROR AL CARGAR PRÉSTAMOS ===");
        e.printStackTrace();
        System.out.println("=================================");
    }
}



// Método auxiliar para obtener el ID del préstamo desde la fila seleccionada
private int obtenerIdPrestamoDesdeFila(int filaSeleccionada) {
    try {
        String dniLector = tblPrestamosActuales.getValueAt(filaSeleccionada, 0).toString();
        String isbn = tblPrestamosActuales.getValueAt(filaSeleccionada, 3).toString();
        
        PrestamoDAO prestamoDAO = new PrestamoDAO();
        return prestamoDAO.obtenerIdPrestamoPorDniEIsbn(dniLector, isbn, SesionActual.dni);
        
    } catch (Exception e) {
        e.printStackTrace();
        return -1;
    }
}

// Método para mostrar solo los préstamos del bibliotecario logueado
public void mostrarMisPrestamos() {
    try {
        PrestamoDAO prestamoDAO = new PrestamoDAO();
        List<Prestamo> listaPrestamos = prestamoDAO.obtenerPrestamosPorBibliotecario(SesionActual.dni);
        
        cargarPrestamosEnTabla(listaPrestamos, "Mis Préstamos");
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar mis préstamos: " + e.getMessage(), 
                                    "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}

// Método para mostrar TODOS los préstamos
public void mostrarTodosLosPrestamos() {
    try {
        PrestamoDAO prestamoDAO = new PrestamoDAO();
        List<Prestamo> listaPrestamos = prestamoDAO.obtenerTodosLosPrestamos();
        
        cargarPrestamosEnTabla(listaPrestamos, "Todos los Préstamos");
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar todos los préstamos: " + e.getMessage(), 
                                    "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}

// Método para buscar préstamos
public void buscarPrestamos() {
    try {
        String textoBusqueda = txtBuscarPrestamos.getText().trim();
        String estadoSeleccionado = (String) cbxEstadoPrestamo.getSelectedItem();
        
        PrestamoDAO prestamoDAO = new PrestamoDAO();
        List<Prestamo> listaPrestamos;
        
        if (!textoBusqueda.isEmpty() && !textoBusqueda.equals("Buscar préstamos....")) {
            // Buscar por DNI o ISBN
            if (textoBusqueda.matches("\\d+")) { // Si es solo números, buscar por DNI
                listaPrestamos = prestamoDAO.buscarPrestamos("dni", textoBusqueda);
            } else { // Si tiene letras, buscar por ISBN
                listaPrestamos = prestamoDAO.buscarPrestamos("isbn", textoBusqueda);
            }
        } else if (!estadoSeleccionado.equals("activo")) { // Cambia "Todos" por "activo" según tu ComboBox
            // Buscar por estado
            listaPrestamos = prestamoDAO.buscarPrestamos("estado", estadoSeleccionado);
        } else {
            // Si no hay criterios, mostrar todos
            listaPrestamos = prestamoDAO.obtenerTodosLosPrestamos();
        }
        
        cargarPrestamosEnTabla(listaPrestamos, "Resultados de Búsqueda");
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al buscar préstamos: " + e.getMessage(), 
                                    "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}
// Método genérico para cargar préstamos en la tabla
private void cargarPrestamosEnTabla(List<Prestamo> listaPrestamos, String titulo) {
    DefaultTableModel modelo = (DefaultTableModel) tblPrestamosActuales.getModel();
    modelo.setRowCount(0); // Limpiar tabla
    
    for (Prestamo prestamo : listaPrestamos) {
        Object[] fila = {
            prestamo.getDniLector(),
            prestamo.getNombresLector(),
            prestamo.getTituloLibro(),
            prestamo.getIsbn(),
            prestamo.getFechaPrestamo(),
            prestamo.getFechaDevolucion(),
            prestamo.getEstado()
        };
        modelo.addRow(fila);
    }
    
    JOptionPane.showMessageDialog(this, 
        "Se encontraron " + listaPrestamos.size() + " préstamos - " + titulo,
        "Información", 
        JOptionPane.INFORMATION_MESSAGE);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnLibros;
    private javax.swing.JButton btnMisPrestamos;
    private javax.swing.JButton btnPrestamos;
    private javax.swing.JButton btnRegistrarDevolucion;
    private javax.swing.JButton btnRegistrarNPrestamo;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVerTodosLosPrestamos;
    private javax.swing.JComboBox<String> cbxEstadoPrestamo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombreBibliotecario;
    private javax.swing.JTable tblPrestamosActuales;
    private javax.swing.JTextField txtBuscarPrestamos;
    // End of variables declaration//GEN-END:variables
}
