/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SistemaBibliotecario.VistaAdmin;

import SistemaBibliotecario.ControladorAdmin.ReportesController;
import SistemaBibliotecario.Modelos.SesionActual;

/**
 *
 * @author User
 */
public class reportes extends javax.swing.JPanel {

    private ReportesController controller;

    /**
     * Creates new form reportes
     */
    public reportes() {
        initComponents();
        controller = new ReportesController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jdcDesdePrestamos = new com.toedter.calendar.JDateChooser();
        jdcHastaPrestamos = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbxEstadoPrestamos = new javax.swing.JComboBox<>();
        btnGenerarReportePrestamo = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jdcDesdeLibros = new com.toedter.calendar.JDateChooser();
        jdcHastaLibro = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jrtbnMenosPrestados = new javax.swing.JRadioButton();
        cbxCategoria = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jrbtnPopulares = new javax.swing.JRadioButton();
        btnGenerarReporteLibros = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jdcDesdeusuarios = new com.toedter.calendar.JDateChooser();
        jdcHastausuarios = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnGenerarReporteUsuarios = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnBibliotecarios = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        lblNombreBibliotecario = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("VISTA BIBLIOTECARIOS");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.jpeg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 40, 110, 80));

        jPanel3.setBackground(new java.awt.Color(19, 38, 76));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ventana Reportes");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addContainerGap(786, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 900, 30));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel6.setText("Hasta");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, 20));
        jPanel4.add(jdcDesdePrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));
        jPanel4.add(jdcHastaPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("Reporte de Prestamos");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel11.setText("Desde");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 20));

        jPanel4.add(cbxEstadoPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, -1));

        btnGenerarReportePrestamo.setBackground(new java.awt.Color(19, 38, 76));
        btnGenerarReportePrestamo.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnGenerarReportePrestamo.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarReportePrestamo.setText("Generar Reporte");
        btnGenerarReportePrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReportePrestamoActionPerformed(evt);
            }
        });
        jPanel4.add(btnGenerarReportePrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 190, 50));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 710, 100));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Reporte de Libros");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 20));
        jPanel5.add(jdcDesdeLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));
        jPanel5.add(jdcHastaLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel13.setText("Desde");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel14.setText("Categoria");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 70, 20));

        jrtbnMenosPrestados.setText("Menos prestados");
        jPanel5.add(jrtbnMenosPrestados, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        jPanel5.add(cbxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 120, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel15.setText("Hasta");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, 20));

        jrbtnPopulares.setText("Mas populares");
        jPanel5.add(jrbtnPopulares, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        btnGenerarReporteLibros.setBackground(new java.awt.Color(19, 38, 76));
        btnGenerarReporteLibros.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnGenerarReporteLibros.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarReporteLibros.setText("Generar Reporte");
        btnGenerarReporteLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteLibrosActionPerformed(evt);
            }
        });
        jPanel5.add(btnGenerarReporteLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 190, 50));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 710, 100));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(jdcDesdeusuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));
        jPanel6.add(jdcHastausuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel12.setText("Desde");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel10.setText("Hasta");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, 20));

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 102));
        jLabel16.setText("Reporte de Usuarios");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 20));

        btnGenerarReporteUsuarios.setBackground(new java.awt.Color(19, 38, 76));
        btnGenerarReporteUsuarios.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnGenerarReporteUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarReporteUsuarios.setText("Generar Reporte");
        btnGenerarReporteUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteUsuariosActionPerformed(evt);
            }
        });
        jPanel6.add(btnGenerarReporteUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 190, 50));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 710, 80));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel8.setText("Informes Recientes");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, -1, 20));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel17.setText(". Reporte Generado - Usuarios");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel19.setText(". Reporte Generado - Prestamos");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel20.setText(". Reporte Generado - Libros");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 710, 200));

        jPanel2.setBackground(new java.awt.Color(19, 38, 76));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBibliotecarios.setBackground(new java.awt.Color(0, 51, 102));
        btnBibliotecarios.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnBibliotecarios.setForeground(new java.awt.Color(255, 255, 255));
        btnBibliotecarios.setText("BIBLIOTECARIOS");
        btnBibliotecarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBibliotecariosActionPerformed(evt);
            }
        });
        jPanel2.add(btnBibliotecarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 240, 80));

        btnUsuarios.setBackground(new java.awt.Color(0, 51, 102));
        btnUsuarios.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setText("USUARIOS");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        jPanel2.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 240, 80));

        btnInicio.setBackground(new java.awt.Color(0, 51, 102));
        btnInicio.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("INICIO");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        jPanel2.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 99, 240, 80));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("REPORTES");
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 240, 80));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BiblioSys");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 30, -1, -1));

        jButton9.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton9.setText("SALIR");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 621, 240, 44));

        lblNombreBibliotecario.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        lblNombreBibliotecario.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreBibliotecario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreBibliotecario.setText("                                ");
        lblNombreBibliotecario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(lblNombreBibliotecario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 569, 240, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBibliotecariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBibliotecariosActionPerformed
        controller.navegarABibliotecarios();
    }//GEN-LAST:event_btnBibliotecariosActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        controller.navegarAInicio();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        controller.navegarAUsuarios();
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        controller.cerrarSesion();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed
        // Este método parece no estar en uso, se puede eliminar
    }//GEN-LAST:event_btnGenerarReporteActionPerformed

    private void btnGenerarReportePrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReportePrestamoActionPerformed
        controller.generarReportePrestamos();
    }//GEN-LAST:event_btnGenerarReportePrestamoActionPerformed

    private void btnGenerarReporteLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteLibrosActionPerformed
        controller.generarReporteLibros();
    }//GEN-LAST:event_btnGenerarReporteLibrosActionPerformed

    private void btnGenerarReporteUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteUsuariosActionPerformed
        controller.generarReporteUsuarios();
    }//GEN-LAST:event_btnGenerarReporteUsuariosActionPerformed

    // ========== MÉTODOS GETTER PARA EL CONTROLADOR ==========
    
    public javax.swing.JComboBox<String> getCbxCategoria() { 
        return cbxCategoria; 
    }

    public javax.swing.JComboBox<String> getCbxEstadoPrestamos() { 
        return cbxEstadoPrestamos; 
    }

    public javax.swing.JLabel getLblNombreBibliotecario() { 
        return lblNombreBibliotecario; 
    }

    public com.toedter.calendar.JDateChooser getJdcDesdePrestamos() { 
        return jdcDesdePrestamos; 
    }

    public com.toedter.calendar.JDateChooser getJdcHastaPrestamos() { 
        return jdcHastaPrestamos; 
    }

    public com.toedter.calendar.JDateChooser getJdcDesdeLibros() { 
        return jdcDesdeLibros; 
    }

    public com.toedter.calendar.JDateChooser getJdcHastaLibro() { 
        return jdcHastaLibro; 
    }

    public com.toedter.calendar.JDateChooser getJdcDesdeusuarios() { 
        return jdcDesdeusuarios; 
    }

    public com.toedter.calendar.JDateChooser getJdcHastausuarios() { 
        return jdcHastausuarios; 
    }

    public javax.swing.JRadioButton getJrbtnPopulares() { 
        return jrbtnPopulares; 
    }

    public javax.swing.JRadioButton getJrtbnMenosPrestados() { 
        return jrtbnMenosPrestados; 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBibliotecarios;
    private javax.swing.JButton btnGenerarReporteLibros;
    private javax.swing.JButton btnGenerarReportePrestamo;
    private javax.swing.JButton btnGenerarReporteUsuarios;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JComboBox<String> cbxEstadoPrestamos;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private com.toedter.calendar.JDateChooser jdcDesdeLibros;
    private com.toedter.calendar.JDateChooser jdcDesdePrestamos;
    private com.toedter.calendar.JDateChooser jdcDesdeusuarios;
    private com.toedter.calendar.JDateChooser jdcHastaLibro;
    private com.toedter.calendar.JDateChooser jdcHastaPrestamos;
    private com.toedter.calendar.JDateChooser jdcHastausuarios;
    private javax.swing.JRadioButton jrbtnPopulares;
    private javax.swing.JRadioButton jrtbnMenosPrestados;
    private javax.swing.JLabel lblNombreBibliotecario;
    // End of variables declaration//GEN-END:variables
}