/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SistemaBibliotecario.VistaAdmin;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import SistemaBibliotecario.Dao.LectorDAO;
import SistemaBibliotecario.VistaLogin.login;
import java.util.List;

/**
 *
 * @author User
 */
public class usuarios extends javax.swing.JPanel {
private LectorDAO lectorDAO;

    /**
     * Creates new form usuarios
     */
    public usuarios() {
        initComponents();
    lectorDAO = new LectorDAO();
    cargarLectores();
    mostrarTotalUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnBibliotecarios = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtApellidoP = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtApellidoM = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        jTextField7 = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("GESTION DE BIBLIOTECARIOS");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(19, 38, 76));

        btnBibliotecarios.setBackground(new java.awt.Color(0, 51, 102));
        btnBibliotecarios.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnBibliotecarios.setForeground(new java.awt.Color(255, 255, 255));
        btnBibliotecarios.setText("BIBLIOTECARIOS");
        btnBibliotecarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBibliotecariosActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("USUARIOS");

        btnInicio.setBackground(new java.awt.Color(0, 51, 102));
        btnInicio.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("INICIO");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnReportes.setBackground(new java.awt.Color(0, 51, 102));
        btnReportes.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setText("REPORTES");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BiblioSys");

        jButton9.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton9.setText("SALIR");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBibliotecarios, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBibliotecarios, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 700));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.jpeg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 40, 110, 80));

        jPanel3.setBackground(new java.awt.Color(19, 38, 76));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Inicio");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addContainerGap(866, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 910, 30));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel6.setText("Dni");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 17, -1, 10));
        jPanel4.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 138, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel7.setText("Nombre");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel8.setText("Direccion");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel9.setText("Email");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, -1));
        jPanel4.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 138, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel10.setText("Apellido Materno");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, -1, -1));
        jPanel4.add(txtApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 138, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel11.setText("Apellido Paterno");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));
        jPanel4.add(txtApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 138, -1));
        jPanel4.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 138, -1));
        jPanel4.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 138, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel13.setText("Telefono");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));
        jPanel4.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 138, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 770, 110));

        tblUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellidos", "Email", "Fecha Creación ", "Ultimo Acceso"
            }
        ));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 890, 460));
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 390, 30));

        btnBuscar.setBackground(new java.awt.Color(19, 38, 76));
        btnBuscar.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel12.setText("Total de Usuarios");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 190, -1, -1));
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 190, 138, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBibliotecariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBibliotecariosActionPerformed
 javax.swing.JFrame frame = new javax.swing.JFrame("Gestión de Bibliotecarios");
    frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
    frame.setContentPane(new bibliotecarios()); // agrega el panel
    frame.pack(); // ajusta al tamaño preferido
    frame.setLocationRelativeTo(null); // centra la ventana
    frame.setVisible(true); // muestra la nueva ventana

    // Cierra la ventana actual
    javax.swing.SwingUtilities.getWindowAncestor(this).dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_btnBibliotecariosActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
 javax.swing.JFrame frame = new javax.swing.JFrame("Inicio");
    frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
    frame.setContentPane(new inicio()); // agrega el panel
    frame.pack(); // ajusta al tamaño preferido
    frame.setLocationRelativeTo(null); // centra la ventana
    frame.setVisible(true); // muestra la nueva ventana

    // Cierra la ventana actual
    javax.swing.SwingUtilities.getWindowAncestor(this).dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
 javax.swing.JFrame frame = new javax.swing.JFrame("Gestión de Reportes");
    frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
    frame.setContentPane(new reportes()); // agrega el panel
    frame.pack(); // ajusta al tamaño preferido
    frame.setLocationRelativeTo(null); // centra la ventana
    frame.setVisible(true); // muestra la nueva ventana

    // Cierra la ventana actual
    javax.swing.SwingUtilities.getWindowAncestor(this).dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_btnReportesActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
login view = new login();  
    view.setLocationRelativeTo(null); // Centrar la ventana
    view.setVisible(true); // Mostrar el login

    // Cerrar la ventana actual
    javax.swing.SwingUtilities.getWindowAncestor(this).dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
                buscarLectores();
// TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
try {
        int filaSeleccionada = tblUsuarios.getSelectedRow();
        
        if (filaSeleccionada >= 0) {
            // Obtener el EMAIL de la fila seleccionada (columna 2)
            String email = tblUsuarios.getValueAt(filaSeleccionada, 2).toString();
            
            // Buscar datos completos por EMAIL
            buscarDatosCompletosPorEmail(email);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al seleccionar usuario: " + e.getMessage(), 
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    }
//GEN-LAST:event_tblUsuariosMouseClicked

  private void buscarDatosCompletosPorEmail(String email) {
    try {
        Object[] usuarioCompleto = lectorDAO.obtenerUsuarioCompletoPorEmail(email);
        
        if (usuarioCompleto != null) {
            // Llenar los campos de texto
            txtDni.setText(usuarioCompleto[0].toString());
            txtNombre.setText(usuarioCompleto[1].toString());
            txtApellidoP.setText(usuarioCompleto[2].toString());
            txtApellidoM.setText(usuarioCompleto[3].toString());
            txtDireccion.setText(usuarioCompleto[4].toString());
            txtTelefono.setText(usuarioCompleto[5].toString());
            txtEmail.setText(usuarioCompleto[6].toString());
            
            // Hacer los campos de solo lectura
            setCamposSoloLectura();
        } else {
            JOptionPane.showMessageDialog(this, "No se encontraron los datos completos del usuario.", 
                "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar datos del usuario: " + e.getMessage(), 
            "Error", JOptionPane.ERROR_MESSAGE);
    }
}


private void setCamposSoloLectura() {
    txtDni.setEditable(false);
    txtNombre.setEditable(false);
    txtApellidoP.setEditable(false);
    txtApellidoM.setEditable(false);
    txtDireccion.setEditable(false);
    txtTelefono.setEditable(false);
    txtEmail.setEditable(false);
}

    // Método para cargar los lectores en la tabla
// Método para cargar los lectores (actualizado)
private void cargarLectores() {
    try {
        DefaultTableModel model = (DefaultTableModel) tblUsuarios.getModel();
        model.setRowCount(0); // Limpiar tabla
        
        List<Object[]> lectores = lectorDAO.listarLector();
        
        if (lectores.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay usuarios lectores registrados.", 
                "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            for (Object[] lector : lectores) {
                // Crear nueva fila con solo las 5 columnas visibles
                Object[] filaMostrar = new Object[5];
                filaMostrar[0] = lector[1]; // Nombre (posición 1 del array del DAO)
                filaMostrar[1] = lector[2]; // Apellidos (posición 2)
                filaMostrar[2] = lector[3]; // Email (posición 3) - ¡IMPORTANTE para la búsqueda!
                filaMostrar[3] = lector[4]; // Fecha Creación (posición 4)
                filaMostrar[4] = lector[5]; // Último Acceso (posición 5)
                
                model.addRow(filaMostrar);
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar usuarios: " + e.getMessage(), 
            "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}

// Método para mostrar el total de usuarios
private void mostrarTotalUsuarios() {
    try {
        List<Object[]> lectores = lectorDAO.listarLector();
        int total = lectores.size();
        jTextField9.setText(String.valueOf(total));
    } catch (Exception e) {
        jTextField9.setText("0");
        System.err.println("Error al contar usuarios: " + e.getMessage());
    }
}

// Método para buscar lectores (si quieres implementar el botón Buscar)
private void buscarLectores() {
    String criterio = jTextField7.getText().trim();
    
    if (criterio.isEmpty()) {
        cargarLectores();
        return;
    }
    
    try {
        DefaultTableModel model = (DefaultTableModel) tblUsuarios.getModel();
        model.setRowCount(0);
        
        List<Object[]> lectores = lectorDAO.buscarLectorPorDniEmailNombre(criterio);
        
        if (lectores.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "No se encontraron usuarios con: " + criterio, 
                "Búsqueda", JOptionPane.INFORMATION_MESSAGE);
        } else {
            for (Object[] lector : lectores) {
                // Crear nueva fila solo con las columnas que quieres mostrar
                Object[] filaMostrar = new Object[5];
                filaMostrar[0] = lector[1]; // Nombre
                filaMostrar[1] = lector[2]; // Apellidos
                filaMostrar[2] = lector[3]; // Email
                filaMostrar[3] = lector[4]; // Fecha Creación
                filaMostrar[4] = lector[5]; // Último Acceso
                
                model.addRow(filaMostrar);
            }
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error en la búsqueda: " + e.getMessage(), 
            "Error", JOptionPane.ERROR_MESSAGE);
    }
}

// Método para configurar las columnas de la tabla
private void configurarTabla() {
    DefaultTableModel model = (DefaultTableModel) tblUsuarios.getModel();
    model.setColumnIdentifiers(new String[]{
        "Nombre", 
        "Apellidos", 
        "Email", 
        "Fecha Creación", 
        "Último Acceso"
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBibliotecarios;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
